### PR TITLE
Fix incorrect Tags/Tagsets + Namespace change.

### PR DESCRIPTION
**Pull request by jbkoh**
In TagSets.csv:
PreHeat -> Preheat
WaterSystem -> Water System
SolarPanel -> Solar Panel
ThermalEnergyStorage -> Thermal Energy Storage
ExhaustSystem -> Exhaust System
LightingSystem -> Lighting System
FireControlPanel -> Fire Control Panel
ExhaustFan -> Exhaust Fan
ReturnFan -> Return Fan
SupplyFan -> Supply Fan
FumeHood -> Fume Hood
EmergencyGenerator -> Emergency Generator
HeatExchanger -> Heat Exchanger

In Tags.csv:
Remove left column of the above list.
Fix class of Dual, Band, Dead.

namespace from buildsys.org to brickschema.org

### CODE REVIEW

**Comment by gtfierro** [comment]
Are you going to regenerate the Brick files after this? Would it make sense to include the Brick update in this PR?

**Comment by jbkoh** [comment]
Update the ttl files too. However, I accidentally pushed the namespace fix commit to the repo before updating this. (Wanted to make separate PRs while I am resolving the conflict due to the Joern's push.) 
So, I'd appreciate if you could review the namespace fix commit together in this PR. Sorry for the confusion.

**Comment by gtfierro** [comment]
Where did Joern's commits come from? Why is he pushing into master?

**Comment by jbkoh** [comment]
yes



With regards,
Jason Koh

**Comment by jbkoh** [comment]
I don't know why. He may just have not known the policy.



With regards,
Jason Koh

**Comment by gtfierro** [comment]
That is not a yes or no question...

**Comment by gtfierro** [comment]
Is this PR ready to be reviewed? Or are there more changes to push?

**Comment by jbkoh** [comment]
Mine must be ready. I haven't looked into Joern's.

**Comment by gtfierro** [comment]
Joern doesn't have a pull request. He unfortunately just pushed directly into master, so hopefully nothing broke as a result of that.

Have you run any of the application queries against the latest version of the Brick files and buildings? Do we know if anything has changed from a usage standpoint?

**Comment by jbkoh** [comment]
Nothing affects the demo queries except the namespaces. I updated the
namespaces in apps too.



With regards,
Jason Koh

**Pull request merged**
