### PR TITLE
1.0.3

### PR DESCRIPTION
**Pull request by jbkoh**
- Add License in ontologies (#41)
- Alarm Setpoint to Setpoint (#40)
- Add def of first class Points (#34)
- Change Meter to Equipment (#34)
- Clarify Occupancy-related Points (#33)
- Add Shading Devices (#30)
- Add some TagSets (#12)
- Change isLocatedIn to hasLocation (#24)
- Fix bugs
    - Duplicated CO2 Sensor (#27)
    - Resource is subClassOf Point (#23)
    - Fix some incorrect TagSets (#14)

### CODE REVIEW

**Comment by jbkoh** [comment]
hold it to accept the PR for a few minutes.

**Comment by gtfierro** [comment]
Can I review this tomorrow before we merge it in?

**Comment by jbkoh** [comment]
Sure.

**Comment by gtfierro** [comment]
LGTM

**Comment by jbkoh** [comment]
@gtfierro so, are you running it?

**Comment by gtfierro** [comment]
The PR looks good to me

**Comment by jbkoh** [comment]
Okay, thanks for reviewing this together. I merge it now.

**Pull request merged**
